package com.stockmanagement.domain.payment.infrastructure.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * Payload received from TossPayments webhook notifications.
 *
 * <p>TossPayments sends HTTP POST requests to our webhook endpoint whenever
 * payment status changes. We must respond with HTTP 2xx within 10 seconds;
 * otherwise TossPayments retries up to 7 times before marking the webhook as failed.
 *
 * <p>Example payload:
 * <pre>{@code
 * {
 *   "eventType": "PAYMENT_STATUS_CHANGED",
 *   "createdAt": "2024-01-01T00:00:00+09:00",
 *   "data": {
 *     "paymentKey": "tviva20240101...",
 *     "orderId": "order-42-abc12345",
 *     "status": "DONE"
 *   }
 * }
 * }</pre>
 *
 * @see <a href="https://docs.tosspayments.com/reference/using-api/webhook-events">Webhook Events</a>
 */
@Getter
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class TossWebhookEvent {

    /**
     * Webhook event type.
     * Currently only {@code "PAYMENT_STATUS_CHANGED"} is handled.
     */
    private String eventType;

    /** ISO-8601 timestamp when the event was generated by TossPayments. */
    private String createdAt;

    /** Event-specific payload. */
    private Data data;

    /** Inner class carrying payment-related webhook data. */
    @Getter
    @NoArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Data {
        /** TossPayments-assigned payment key. */
        private String paymentKey;

        /** Our tossOrderId that was sent to TossPayments. */
        private String orderId;

        /**
         * New payment status.
         * Typical values: "DONE", "CANCELED", "WAITING_FOR_DEPOSIT", "ABORTED".
         */
        private String status;
    }
}
