global:
  scrape_interval: 15s       # 15초마다 메트릭 수집
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'stock-management-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    # 메트릭에 애플리케이션 레이블 추가
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'stock-app'
